/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eqsolver_AlgebricCubicEquationSolver */

#ifndef _Included_eqsolver_AlgebricCubicEquationSolver
#define _Included_eqsolver_AlgebricCubicEquationSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eqsolver_AlgebricCubicEquationSolver
 * Method:    solve
 * Signature: ([DDDDD)I
 */
JNIEXPORT jint JNICALL Java_eqsolver_AlgebricCubicEquationSolver_solve
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
