/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example01_GeneratoreInteri */

#ifndef _Included_example01_GeneratoreInteri
#define _Included_example01_GeneratoreInteri
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example01_GeneratoreInteri
 * Method:    generaIntero
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_example01_GeneratoreInteri_generaIntero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
