/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example02_Randomizer */

#ifndef _Included_example02_Randomizer
#define _Included_example02_Randomizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example02_Randomizer
 * Method:    randomNumbers
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_example02_Randomizer_randomNumbers
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
